### ISSUE TITLE
Add a licence

### ISSUE THREAD

**Issue by eBildungslabor** [breck7/scroll#87]
It would be great if you could add an open licence to the project. Or is there already one and I just missed it? Thanks!

**Comment by breck7** [comment]
Can someone else explain please?

**Comment by runvnc** [comment]
I agree with the sentiment in principle, but since we have so many lawyers on this planet, I have to say that actually leaving the license out is a significant error, as it discourages involvement of developers or businesses that have a practical understanding of the business world.

Because when it comes down to it, we can't rationally count on a comment in an issue to hold the weight of a license. It would be very easy for you to decide to add an AGPL license at any point. And then one could argue with a lawyer, well, he effectively changed the "license" because he stated that it was in the public domain previously. But I think that most lawyers would just say that was a naive interpretation and there never was a license.  So it would be counted as a business error to have adopted the platform.

I hope you will consider the MIT License.

**Comment by breck7** [comment]
I appreciate the sentiment @runvnc , but this is a fight we have decided to fight and we know we can win.

Don't worry, we're building an army and a warchest.

**Comment by runvnc** [comment]
I think that's terrific that you are fighting for public domain.  And I really appreciate that and my comments are not trying to take that away or contradict it at all.

But are you absolutely certain that in order to do so, it is critical to INSIST that there is no file named LICENSE?

https://github.com/sqlite/sqlite/blob/master/LICENSE.md

You mention sqlite in one of your posts. You can see in the file above, they simply state:

> The author disclaims copyright to this source code.  In place of
> a legal notice, here is a blessing:
> 
>   *   May you do good and not evil.
>   *   May you find forgiveness for yourself and forgive others.
>   *   May you share freely, never taking more than you give.

**Comment by breck7** [comment]
> But are you absolutely certain that in order to do so, it is critical to INSIST that there is no file named LICENSE?

When you put it like that, I have to say No.


```
https://github.com/sqlite/sqlite/blob/master/LICENSE.md

You mention sqlite in one of your posts. You can see in the file above, they simply state:

The author disclaims copyright to this source code. In place of
a legal notice, here is a blessing:

May you do good and not evil.
May you find forgiveness for yourself and forgive others.
May you share freely, never taking more than you give.
```

That's lovely. Ok, I would accept this as a pull request, if someone copies sqlite verbatim.

**Comment by runvnc** [comment]
Awesome thanks.  I am thinking of using that license in my agent framework also. I will do the PR within the next couple of hours unless someone beats me to it.
